# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ServerConfigurator.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_ServerConfigurator(object):
    def setupUi(self, ServerConfigurator):
        ServerConfigurator.setObjectName("ServerConfigurator")
        ServerConfigurator.resize(334, 361)
        ServerConfigurator.setMinimumSize(QtCore.QSize(334, 361))
        ServerConfigurator.setMaximumSize(QtCore.QSize(334, 361))
        self.centralwidget = QtWidgets.QWidget(ServerConfigurator)
        self.centralwidget.setObjectName("centralwidget")
        self.connection_type_combo = QtWidgets.QComboBox(self.centralwidget)
        self.connection_type_combo.setGeometry(QtCore.QRect(10, 90, 86, 21))
        self.connection_type_combo.setObjectName("connection_type_combo")
        self.connection_type_combo.addItem("")
        self.connection_type_combo.addItem("")
        self.Download = QtWidgets.QPushButton(self.centralwidget)
        self.Download.setGeometry(QtCore.QRect(245, 290, 81, 21))
        self.Download.setObjectName("Download")
        self.security_version_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.security_version_label_2.setGeometry(QtCore.QRect(180, 320, 151, 20))
        self.security_version_label_2.setObjectName("security_version_label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 60, 451, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.security_version_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.security_version_label_3.setGeometry(QtCore.QRect(10, 70, 361, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.security_version_label_3.setFont(font)
        self.security_version_label_3.setObjectName("security_version_label_3")
        self.static_ip_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.static_ip_checkbox.setGeometry(QtCore.QRect(10, 120, 226, 20))
        self.static_ip_checkbox.setObjectName("static_ip_checkbox")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 231, 46))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.security_version_label = QtWidgets.QLabel(self.layoutWidget)
        self.security_version_label.setObjectName("security_version_label")
        self.verticalLayout_2.addWidget(self.security_version_label)
        self.security_version_combo = QtWidgets.QComboBox(self.layoutWidget)
        self.security_version_combo.setObjectName("security_version_combo")
        self.security_version_combo.addItem("")
        self.security_version_combo.addItem("")
        self.verticalLayout_2.addWidget(self.security_version_combo)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pop_label = QtWidgets.QLabel(self.layoutWidget)
        self.pop_label.setObjectName("pop_label")
        self.verticalLayout_3.addWidget(self.pop_label)
        self.pop_text = QtWidgets.QLineEdit(self.layoutWidget)
        self.pop_text.setObjectName("pop_text")
        self.verticalLayout_3.addWidget(self.pop_text)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 35, 75, 21))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 140, 228, 174))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.connection_type_label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.connection_type_label_2.setObjectName("connection_type_label_2")
        self.horizontalLayout_3.addWidget(self.connection_type_label_2)
        self.ip_address_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.ip_address_input.setObjectName("ip_address_input")
        self.horizontalLayout_3.addWidget(self.ip_address_input)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connection_type_label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.connection_type_label_3.setObjectName("connection_type_label_3")
        self.horizontalLayout_2.addWidget(self.connection_type_label_3)
        self.netmask_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.netmask_input.setObjectName("netmask_input")
        self.horizontalLayout_2.addWidget(self.netmask_input)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connection_type_label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.connection_type_label_4.setObjectName("connection_type_label_4")
        self.horizontalLayout.addWidget(self.connection_type_label_4)
        self.gateway_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.gateway_input.setObjectName("gateway_input")
        self.horizontalLayout.addWidget(self.gateway_input)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.connection_type_label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.connection_type_label_5.setObjectName("connection_type_label_5")
        self.horizontalLayout_5.addWidget(self.connection_type_label_5)
        self.port_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.port_input.setObjectName("port_input")
        self.horizontalLayout_5.addWidget(self.port_input)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.available_wifis = QtWidgets.QComboBox(self.layoutWidget1)
        self.available_wifis.setObjectName("available_wifis")
        self.horizontalLayout_6.addWidget(self.available_wifis)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.wifi_password = QtWidgets.QLineEdit(self.layoutWidget1)
        self.wifi_password.setObjectName("wifi_password")
        self.horizontalLayout_7.addWidget(self.wifi_password)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.connection_type_combo.raise_()
        self.Download.raise_()
        self.security_version_label_2.raise_()
        self.pushButton.raise_()
        self.line.raise_()
        self.security_version_label_3.raise_()
        self.static_ip_checkbox.raise_()
        ServerConfigurator.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ServerConfigurator)
        self.statusbar.setObjectName("statusbar")
        ServerConfigurator.setStatusBar(self.statusbar)

        self.retranslateUi(ServerConfigurator)
        QtCore.QMetaObject.connectSlotsByName(ServerConfigurator)

    def retranslateUi(self, ServerConfigurator):
        _translate = QtCore.QCoreApplication.translate
        ServerConfigurator.setWindowTitle(_translate("ServerConfigurator", "ServerConfigurator"))
        self.connection_type_combo.setItemText(0, _translate("ServerConfigurator", "Ethernet"))
        self.connection_type_combo.setItemText(1, _translate("ServerConfigurator", "Wi-Fi"))
        self.Download.setText(_translate("ServerConfigurator", "Download"))
        self.security_version_label_2.setText(_translate("ServerConfigurator", "Server Configurator v1.0"))
        self.security_version_label_3.setText(_translate("ServerConfigurator", "OPC UA Server Configuration"))
        self.static_ip_checkbox.setText(_translate("ServerConfigurator", "Static IP (only Ethernet)"))
        self.security_version_label.setText(_translate("ServerConfigurator", "Security"))
        self.security_version_combo.setItemText(0, _translate("ServerConfigurator", "No"))
        self.security_version_combo.setItemText(1, _translate("ServerConfigurator", "AES-CTR"))
        self.pop_label.setText(_translate("ServerConfigurator", "Server Password"))
        self.pushButton.setText(_translate("ServerConfigurator", "Connect"))
        self.connection_type_label_2.setText(_translate("ServerConfigurator", "IP Adress"))
        self.connection_type_label_3.setText(_translate("ServerConfigurator", "Netmask"))
        self.connection_type_label_4.setText(_translate("ServerConfigurator", "Gateway"))
        self.connection_type_label_5.setText(_translate("ServerConfigurator", "Port (Default 4840)"))
        self.label.setText(_translate("ServerConfigurator", "Available Wi-Fis"))
        self.label_2.setText(_translate("ServerConfigurator", "Wi-Fi Password"))
